---
title: "COVID19"
author: "by Sahir Bhatnagar"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: false
    number_sections: true
    toc_depth: 4
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pull data

```{r}
# remotes::install_github("GuangchuangYu/nCov2019")
library(nCov2019)
library(tidyverse)
library(ggrepel)

y <- load_nCov2019(lang = 'en', source = 'github')
# head(summary(y))
DT <- y['global']
# head(DT)
DT$country %>% table
str(DT)

# without China
DT <- DT %>% 
  group_by(country) %>% 
  mutate(label = if_else(time == max(time), as.character(country), NA_character_)) %>% 
  ungroup()

# DT$label %>% table(useNA = "al")

# DT %>% filter(!is.na(label))

# head(DT)

# dev.off()

pacman::p_load(plotly)

p <- 
  DT %>% 
  filter(country != "China") %>% 
  ggplot(data = ., mapping = aes(x = time, y = log(cum_confirm))) + 
  geom_line(mapping = aes(colour = country), size = 1) + 
  xlab(NULL) + 
  # ylab(NULL) + 
  scale_x_date(date_labels = "%Y-%m-%d",
               limits = c(as.Date("2020-02-01"), as.Date("2020-03-04"))) +
  theme_minimal() +   
  # theme(legend.position = 'none') + 
  geom_label_repel(mapping = aes(label = label))
```



```{r, fig.width=12, fig.height=9, warning=FALSE}
ggplotly(p)
```

